/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'daisuke' at '16/09/24 14:04' with Gradle 2.13
 *
 * @author daisuke, @date 16/09/24 14:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
